### ISSUE TITLE
Name length

### ISSUE THREAD

**Issue by AliceGrey** [Azelphur/PokemonGo-CalcyIV-Renamer#13]
I've noticed that there are some issues with name length and the rename button. On a 1080p phone the rename button is sometimes too far right if the name is long and the script will miss the rename button. Maybe you could have it check name length and then fuzz the rename location to the left or right based upon the name length?

**Comment by Azelphur** [comment]
You can also click the pokemons name to rename, not just the button. As the name is centered, you can never miss it by clicking in the middle. This is what the default does, clicks right in the middle, so you can't miss it. See https://imgur.com/a/gucLtod

If you are having issues - something else is likely the cause, although I'm not sure what, perhaps your wait times are too low.
