### ISSUE TITLE
'rename' action cannot contain whitespaces

### ISSUE THREAD

**Issue by esauvisky** [Azelphur/PokemonGo-CalcyIV-Renamer#15]
I think 'input text' is probably interpreting more than one word as different parameters.
Also, `input text` does not allow most special characters, which to be honest are quite handy for sorting pokémons.

I think the best solution for both problems is to use `clipper` on the opposite way, using the `set` intent:
    
    adb shell am broadcast -a clipper.set -e text {rename_string}

**Comment by Azelphur** [comment]
I agree, using clipboard will also be faster too - I'll get that done soon.

**Comment by esauvisky** [comment]
Jeez, that took me ages...

> Apparently I really have no idea how to work with remote upstream repos. At the very least I managed to get [this one](https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/pull/22) out :smile: Still figuring out how to keep a different local/origin state (I'm not quitting my unicode normalization! :grin: ) and have git not to include those changes in every PR...

**Comment by Azelphur** [comment]
Cool, I've accepted the pull request, so I'm gonna go ahead and close this one.
