### ISSUE TITLE
It appears there is not a condition called 'iv__ne'

### ISSUE THREAD

**Issue by esauvisky** [Azelphur/PokemonGo-CalcyIV-Renamer#16]
In your examples you use only `iv: ` when trying to match it for parity.

Is the documentation wrong and in fact the operators are not completely universal along the conditions or is this a bug?

**Comment by Azelphur** [comment]
The default condition is equal.

`iv: `
`iv: null`
`iv__eq: `
`iv__eq: null`

are all synonymous

So you're checking that iv is null, or that there is no exact IV found (only an IV range)

Are you saying that iv__ne isn't working for you?

**Comment by esauvisky** [comment]
No, that actually works fine. I just assumed the condition existed and, lets say, `iv__ne: 100` would match any pokémon with an exact IV value of anything but 100, i.e.: non hundo ones.

Of course, for that particular case it'd only a matter of defining a `__in: [list]` or using `iv_max__ne: 100`, but I came across trying to use that condition and it didn't work.
