### ISSUE TITLE
Using example config from readme causes error 0

### ISSUE THREAD

**Issue by AliceGrey** [Azelphur/PokemonGo-CalcyIV-Renamer#18]
If I run the script with the default actions it doesn't throw any errors. If I add the example actions it hangs with error 0. (I had to rename the yaml file's to txt for upload)
[log.txt](https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/files/2498527/log.txt)

[notworkingconfig.txt](https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/files/2498529/notworkingconfig.txt)
[workingconfig.txt](https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/files/2498530/workingconfig.txt)

**Comment by Azelphur** [comment]
The docs don't make this clear - but [clipper](https://github.com/majido/clipper/releases) is a dependency for reading back IVs - you need to install it and start the service.

Feel free to reopen if this doesn't resolve your problem
