### ISSUE TITLE
[Critical] Depending on device resolution, it's possible for the script to actually power up a pokemon automatically

### ISSUE THREAD

**Issue by esauvisky** [Azelphur/PokemonGo-CalcyIV-Renamer#47]
This bug is related to the fact that all blacklisted pokémons are taken as `success: failed`.

_Assuming calcy's dialog Close Button (X) is exactly on top of the POWER UP button (happens with 1080x2400 with my particular DPI)_ **This is how to the issue works:**
- If the calcy scan works, but the pokemon is blacklisted,
- No calcy dialog shows up (because the scan didn't fail).
- But the scripts assumes it did (because blacklisted pokemons always "fail")
- So the script clicks on `close_calcy_dialog`, which is exactly on top of the POWER UP button.
- As if this weren't enough, the next tap is `rename` – which, _...drum roll..._ – matches exactly the YES button of the _"Do you want to power up your pokemon" dialog.

**Comment by Azelphur** [comment]
I believe this is resolved now, gonna close it - feel free to reopen if it's still present
