### ISSUE TITLE
Script no longer opens edit box to rename pokemon

### ISSUE THREAD

**Issue by aahern** [Azelphur/PokemonGo-CalcyIV-Renamer#5]
Was working fine until a few weeks ago, now it isn't renaming them any more.
It appraises several times, and then goes to the next Pokemon, here is log output

https://i.imgur.com/Br2Jbiv.png

Device:
Pixel XL
OS: Android 9 Pie
Latest Pokemon Go / CalcyIV

**Comment by Azelphur** [comment]
I've just pushed a rewrite which changes a lot of things, it's faster, but more importantly it also has a config file for you to specify the location of the rename button. It should address this issue. Feel free to reopen if your bug is still present in the rewrite! :)

**Comment by aahern** [comment]
Thanks man! Don't know of any other tools like this so that's great. I was wondering if you think it would be possible to do this on device rather than via adb - was thinking of making something similar via Tasker but it would possibly require root to interact with CalcyIV properly. Alternatively maybe a native Android app could do it via intents and an overlay of its own?

**Comment by JayTurnr** [comment]
I've been wondering if this could be done with a python interpreter on phone as the phones have adb on them too. Probably would require root.

**Comment by Azelphur** [comment]
@aahern @JayTurnr I have a feeling it could "just work" this script works by executing shell commands on the phone mostly (via adb shell) - I haven't looked into it though.

**Comment by JayTurnr** [comment]
I don't imagine ADB tap events would work

**Comment by aahern** [comment]
You could use Tasker + AutoInput without root for tap events. You can tell it to tap a particular location on screen.
