### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by D-Bullock** [Azelphur/PokemonGo-CalcyIV-Renamer#54]
I'm trying to work out what is wrong with the script - it seems to be doing nothing except the initial getting of the pokemon's details then nothing from there. 

I notice there was an update to Calcy, could that have broken things?
Is there a way of getting a less verbose output? I'm having a hard time parsing the logs and working out what's generated by this script and what's just a generic adb log

Sidenote: This library is amazing! Thank you for all your hard work. I don't have any expectation of you fixing my problem but instead I'd like some pointers for where to look to solve it.

**Comment by Azelphur** [comment]
Hi,

We used to have a way of filtering the Android phones logcat, it was discovered that this broke on some phones however and was removed for that reason.

The recent calcy update did indeed break things, however that has already been patched - ensure you are running the latest version of both calcy iv and the iv renamer

If that isn't the issue, then I would search your logs for "Received values".

The way the IV renamer works is:
It sends an intent, tesmath.calcy.ACTION_ANALYZE_SCREEN which causes calcy to do a scan (Search your logs for tesmath.calcy.ACTION_ANALYZE_SCREEN, if its not there, that means the script never asked for a scan)

It watches the phones logs to catch calcy IVs debug messages (Search your logs for "Received values:", if it's not there, Calcy IV didn't respond to the intent)

Immediately after the "Received values:" you should have a line that says "RE_CALCY_IV matched" - if you don't, then the script isn't recognizing your Calcy IV output, make sure you're on the latest versions and paste your received values here so I can fix it

If you get recieved values and RE_CALCY_IV matched, then the problem most likely lies in your locations config

**Comment by D-Bullock** [comment]
Thanks!
