### ISSUE TITLE
Swipe not working on latest

### ISSUE THREAD

**Issue by aahern** [Azelphur/PokemonGo-CalcyIV-Renamer#6]
Hi thanks for the update, it now correctly renames the Pokémon but swiping to the next Pokémon isn't working any more. I'm not solid on ADB but is it because it's using a tap event rather than a swipe event? I'm not aware of an area you can tap to go to the next Pokémon but maybe there is one and if so would be good to know where so I can update the config for my phone. I tried to wire in adb shell swipe but it still didn't work for me. Thanks again for the good work!

**Comment by marob** [comment]
FYI, swipe was causing problem on some devices that have special gestures (see: https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/issues/2#issuecomment-389349812) so it has been replaced by a tap.
You can see the zones allowing to "swipe" to the next/previous pokemon by a tap here: https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/issues/2#issuecomment-397588245

**Comment by aahern** [comment]
Aha thanks! Didn't know those existed, will close issue.
